name: cinema_app
description: Cinema app for Kueski
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cinema_api_client:
    path: packages/cinema_api_client
  cinema_models:
    path: packages/cinema_models
  cinema_ui:
    path: packages/cinema_ui
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  mocktail: ^1.0.4
  movie_repository:
    path: packages/movie_repository
  shared_preferences: ^2.3.2
  shared_storage:
    path: packages/shared_storage

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail_image_network: ^1.2.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - assets/movie_error.png
