name: cinema_api_client
description: cinema api client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cinema_models:
    path: ../cinema_models
  dio: ^5.7.0


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
