name: cinema_models
description: cinema models for app
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.5
  intl: ^0.19.0
  json_annotation: ^4.9.0


dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

