name: movie_repository
description: movies repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cinema_api_client:
    path: ../cinema_api_client
  cinema_models:
    path: ../cinema_models


dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
